### PR TITLE
Prepend javascript-flow to list

### PR DESCRIPTION
**Pull request by aaronjensen**
I tend to want flow checking my program before linters. 
It is faster and it is focused on correctness rather than style.

### CODE REVIEW

**Comment by lbolla** [comment]
I'd rather leave the default to be after any already specified linter, so that "default" linters specified by flycheck itself can take priority. If you want otherwise, why not reordering `flycheck-checkers` in your Emacs configuration?

**Comment by aaronjensen** [comment]
I do, this just seemed like a better default for this type of linter. Other 3rd party linters do this as well, so I thought I'd propose it.

**Comment by lbolla** [comment]
I'll leave the PR open for a bit, in case someone wants to object, and then I'll merge it.

**Comment by lbolla** [comment]
Nobody objected, so I'll go ahead and merge it.

**Comment by aaronjensen** [comment]
Thanks!

**Pull request merged**
