### PR TITLE
Add support for rjsx-mode

### PR DESCRIPTION
**Pull request by a3ammar**
Hi,
I would really love if this supported [rjsx-mode](https://github.com/felipeochoa/rjsx-mode/)

### CODE REVIEW

**Comment by a3ammar** [comment]
Oh, I just found out by reading the other pull requests that I could do the same with `flycheck-add-mode`. Feel free to close this if you feel it shouldn't be added.

**Comment by lbolla** [comment]
Yeah, `flycheck-add-mode` is my preferred solution.

**Comment by wpcarro** [comment]
I feel like this should either be documented or baked into this plugin as using Flow with `rjsx-mode` seems like a common setup, no?

**Comment by lbolla** [comment]
I am not a user of `rjsx-mode` and I wouldn't know if it's a common use case. But I guess it's a harmless enough feature. I'll push a fix.

**Pull request closed without merging**
